export const KeyShortcuts = {
  a: "F3",
  w: "F#3",
  s: "G3",
  e: "G#3",
  d: "A3",
  r: "A#3",
  f: "B3",
  g: "C4",
  y: "C#4",
  h: "D4",
  u: "D#4",
  j: "E4",
  k: "F4",
  o: "F#4",
  l: "G4",
  p: "G#4",
  ";": "A4",
  "[": "A#4",
  "'": "B4",
  "]": "A#4",
};

export const KeyList = [
  // C3
  {
    note: "C3",
    enharmonic: "B#2",
    color: "white",
    label: "C",
    enharmoniclabel: "B#",
    midi: 48,
  },
  {
    note: "C#3",
    enharmonic: "Db3",
    color: "black",
    label: "C#",
    enharmoniclabel: "Db",
    midi: 49,
  },
  {
    note: "D3",
    enharmonic: false,
    color: "white",
    label: "D",
    enharmoniclabel: false,
    midi: 50,
  },
  {
    note: "D#3",
    enharmonic: "Eb3",
    color: "black",
    label: "D#",
    enharmoniclabel: "Eb",
    midi: 51,
  },
  {
    note: "E3",
    enharmonic: "Fb3",
    color: "white",
    label: "E",
    enharmoniclabel: "Fb",
    midi: 52,
  },
  {
    note: "F3",
    enharmonic: "E#3",
    color: "white",
    label: "F",
    enharmoniclabel: "E#",
    midi: 53,
    shortcut: "a",
  },
  {
    note: "F#3",
    enharmonic: "Gb3",
    color: "black",
    label: "F#",
    enharmoniclabel: "Gb",
    midi: 54,
    shortcut: "w",
  },
  {
    note: "G3",
    enharmonic: false,
    color: "white",
    label: "G",
    enharmoniclabel: false,
    midi: 55,
    shortcut: "s",
  },
  {
    note: "G#3",
    enharmonic: "Ab3",
    color: "black",
    label: "G#",
    enharmoniclabel: "Ab",
    midi: 56,
    shortcut: "e",
  },
  {
    note: "A3",
    enharmonic: false,
    color: "white",
    label: "A",
    enharmoniclabel: false,
    midi: 57,
    shortcut: "d",
  },
  {
    note: "A#3",
    enharmonic: "Bb3",
    color: "black",
    label: "A#",
    enharmoniclabel: "Bb",
    midi: 58,
    shortcut: "r",
  },
  {
    note: "B3",
    enharmonic: "Cb4",
    color: "white",
    label: "B",
    enharmoniclabel: "Cb",
    midi: 59,
    shortcut: "f",
  },
  // C4
  {
    note: "C4",
    enharmonic: "B#3",
    color: "white",
    label: "C",
    enharmoniclabel: "B#",
    midi: 48,
    shortcut: "g",
  },
  {
    note: "C#4",
    enharmonic: "Db4",
    color: "black",
    label: "C#",
    enharmoniclabel: "Db",
    midi: 49,
    shortcut: "y",
  },
  {
    note: "D4",
    enharmonic: false,
    color: "white",
    label: "D",
    enharmoniclabel: false,
    midi: 50,
    shortcut: "h",
  },
  {
    note: "D#4",
    enharmonic: "Eb4",
    color: "black",
    label: "D#",
    enharmoniclabel: "Eb",
    midi: 51,
    shortcut: "u",
  },
  {
    note: "E4",
    enharmonic: "Fb4",
    color: "white",
    label: "E",
    enharmoniclabel: "Fb",
    midi: 52,
    shortcut: "j",
  },
  {
    note: "F4",
    enharmonic: "E#4",
    color: "white",
    label: "F",
    enharmoniclabel: "E#",
    midi: 54,
    shortcut: "k",
  },
  {
    note: "F#4",
    enharmonic: "Gb4",
    color: "black",
    label: "F#",
    enharmoniclabel: "Gb",
    midi: 54,
    shortcut: "o",
  },
  {
    note: "G4",
    enharmonic: false,
    color: "white",
    label: "G",
    enharmoniclabel: false,
    midi: 55,
    shortcut: "l",
  },
  {
    note: "G#4",
    enharmonic: "Ab4",
    color: "black",
    label: "G#",
    enharmoniclabel: "Ab",
    midi: 56,
    shortcut: "p",
  },
  {
    note: "A4",
    enharmonic: false,
    color: "white",
    label: "A",
    enharmoniclabel: false,
    midi: 57,
    shortcut: ";",
  },
  {
    note: "A#4",
    enharmonic: "Bb4",
    color: "black",
    label: "A#",
    enharmoniclabel: "Bb",
    midi: 58,
    shortcut: "[",
  },
  {
    note: "B4",
    enharmonic: "Cb5",
    color: "white",
    label: "B",
    enharmoniclabel: "Cb",
    midi: 59,
    shortcut: "'",
  },
  // C5
  {
    note: "C5",
    enharmonic: "B#4",
    color: "white",
    label: "C",
    enharmoniclabel: "B#",
    midi: 48,
  },
  {
    note: "C#5",
    enharmonic: "Db5",
    color: "black",
    label: "C#",
    enharmoniclabel: "Db",
    midi: 49,
  },
  {
    note: "D5",
    enharmonic: false,
    color: "white",
    label: "D",
    enharmoniclabel: false,
    midi: 50,
  },
  {
    note: "D#5",
    enharmonic: "Eb5",
    color: "black",
    label: "D#",
    enharmoniclabel: "Eb",
    midi: 51,
  },
  {
    note: "E5",
    enharmonic: "Fb5",
    color: "white",
    label: "E",
    enharmoniclabel: "Fb",
    midi: 52,
  },
  {
    note: "F5",
    enharmonic: "E#5",
    color: "white",
    label: "F",
    enharmoniclabel: "E#",
    midi: 55,
  },
  {
    note: "F#5",
    enharmonic: "Gb5",
    color: "black",
    label: "F#",
    enharmoniclabel: "Gb",
    midi: 54,
  },
  {
    note: "G5",
    enharmonic: false,
    color: "white",
    label: "G",
    enharmoniclabel: false,
    midi: 55,
  },
  {
    note: "G#5",
    enharmonic: "Ab5",
    color: "black",
    label: "G#",
    enharmoniclabel: "Ab",
    midi: 56,
  },
  {
    note: "A5",
    enharmonic: false,
    color: "white",
    label: "A",
    enharmoniclabel: false,
    midi: 57,
  },
  {
    note: "A#5",
    enharmonic: "Bb5",
    color: "black",
    label: "A#",
    enharmoniclabel: "Bb",
    midi: 58,
  },
  {
    note: "B5",
    enharmonic: "Cb6",
    color: "white",
    label: "B",
    enharmoniclabel: "Cb",
    midi: 59,
  },
];
